services:
  fastapi-app:
    container_name: nikolove18_fastapi
    image: fastapi
    build:
      context: ./
      dockerfile: Dockerfile
    command: uvicorn src.api.main:app --reload --host 0.0.0.0
    volumes:
      - .:/app
      - /layouts:/layouts
    shm_size: '2gb'
    ports:
      - 8000:8000
