services:
  fastapi-app:
    container_name: nikolove18_fastapi
    image: nikolove18
    build:
      context: ./
      dockerfile: Dockerfile
    command: uvicorn src.api.server:app --reload --host 0.0.0.0
    volumes:
      - .:/app
      - /layouts:/layouts
      - /mnt:/mnt
    shm_size: '2gb'
    ports:
      - 8000:8000
